sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t yujia/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true yujia/docker npm run test

deploy:
  provider: elasticbeanstalk
  region: :"ap-southeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-072036813919"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
